account_app/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("register", views.user_register, name="register"),
    path("edit", views.user_edit, name="edit"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('detail/<slug:slug>', views.ArticleDetailView.as_view(), name='article_detail'),
    path('articlelsit', views.ArticleListView.as_view(), name='article_list'),
    path('category/<int:pk>', views.category_detail, name="category_detail"),
    path('search/', views.search, name='search_articles'),
    # path('contactus/', views.ContactUsView.as_view(), name='contact_us'),
    path('contactus/', views.MessageView.as_view(), name='contact_us'),
    path('messages/', views.MessageListView.as_view(), name='message_list'),
    path('message/edit/<int:pk>', views.MessageUpdateView.as_view(), name='message_edit'),
    path('message/delete/<int:pk>', views.DeleteView.as_view(), name='message_delete'),
    path('archive', views.ArchiveIndexArticleView.as_view(), name='archive'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('home_app.urls')),
    path('test/', include('account_app.urls')),
    path('articles/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class ArticleManager(models.Manager):
    def counter(self):
        return len(self.all())

    def published(self):
        return self.filter(status=True)


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    auther = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, related_name="articles")
    title = models.CharField(max_length=70)
    body = models.TextField()
    image = models.ImageField(upload_to="images/article")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now())
    slug = models.SlugField(blank=True, unique=True)
    objects = ArticleManager()

    # pub_date = models.DateTimeField(default=timezone.now())
    # pub_date = models.DateTimeField(default=timezone.datetime(day=20))

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def get_absolute_url(self):
        # return reverse('blog:article_detail', args=[self.id])
        return reverse('blog:article_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.title} - {self.body[:30]}'

    class Meta:
        ordering = ("-created",)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50]


class Message(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.core.validators import ValidationError

from blog.models import Message


######## for test ########
class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=10, label='Your message', required=False)
    text = forms.CharField(max_length=10, label='Your message')

    def clean(self):
        name = self.cleaned_data.get('name')
        text = self.cleaned_data.get('text')
        if name == text:
            raise ValidationError('name and text are same', code='name_text_same')

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if 'a' in name:
            raise ValidationError('a can not be in name')
        return name


########## method 1 #############
# class MessageForms(forms.Form):
#     title = forms.CharField(max_length=100)
#     text = forms.CharField(widget=forms.Textarea())
#     email = forms.EmailField()


########## method 2 ############
class MessageForms(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('title', 'text', 'email')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article, Category, Comment, Message
from django.core.paginator import Paginator
from .forms import ContactUsForm, MessageForms
from django.views.generic.base import View, TemplateView
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView, ArchiveIndexView
from .mixins import CustomLoginRequiredMixin
from django.urls import reverse_lazy


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    if request.POST:
        body = request.POST.get('body')
        parent_id = request.POST.get('parent_id')
        Comment.objects.create(body=body, article=article, user=request.user, parent_id=parent_id)
    return render(request, 'blog/article_detail.html', {'article': article})


def article_list(request):
    articles = Article.objects.all()
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 1)
    objects_list = paginator.get_page(page_number)
    return render(request, 'blog/article_list.html', {'articles': objects_list})


def category_detail(request, pk=None):
    category = get_object_or_404(Category, id=pk)
    articles = category.articles.all()
    return render(request, "blog/article_list.html", {'articles': articles})


def search(request):
    q = request.GET.get('q')
    articles = Article.objects.filter(title__icontains=q)
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 1)
    objects_list = paginator.get_page(page_number)
    return render(request, "blog/article_list.html", {'articles': objects_list})


def contactus(request):
    if request.method == 'POST':
        form = MessageForms(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            email = form.cleaned_data['email']
            Message.objects.create(title=title, text=text, email=email)
            # instance = form.save(commit=True)
    else:
        form = MessageForms()
    return render(request, "blog/contact_us.html", {'form': form})


class ArticleList(TemplateView):
    template_name = "blog/article_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.all()
        return context


class ArticleListView(CustomLoginRequiredMixin, ListView):
    model = Article
    context_object_name = 'articles'
    paginate_by = 1


class ArticleDetailView(DetailView):
    model = Article


class ContactUsView(FormView):
    template_name = "blog/contact_us.html"
    form_class = MessageForms
    success_url = reverse_lazy('home:main')

    def form_valid(self, form):
        form_data = form.cleaned_data
        Message.objects.create(**form_data)
        return super().form_valid(form)


class MessageView(CreateView):
    model = Message
    fields = ('title', 'text')
    success_url = reverse_lazy('home:main')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_messages'] = Message.objects.all()
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.email = self.request.user.email
        instance.save()
        return super().form_valid(form)


class MessageListView(ListView):
    model = Message


class MessageUpdateView(UpdateView):
    model = Message
    fields = ('title', 'text')
    template_name = 'blog/message_update_form.html'
    success_url = reverse_lazy('blog:message_list')


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('blog:message_list')


class ArchiveIndexArticleView(ArchiveIndexView):
    model = Article
    date_field = "updated"

blog/templates/blog/article_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for article in latest %}
 <li>{{ article.pub_date }}: {{ article.title }}</li>
{% endfor %}
</body>
</html>

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static   %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}

      <!-- Banner Ends Here -->
    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src={{ article.image.url }} alt="">
                    </div>
                    <div class="down-content">
                      <span>Lifestyle</span>
                      <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.auther }}</a></li>
                        <li><a href="#">{{ article.created }}</a></li>
                        <li><a href="#">10 Comments</a></li>
                      </ul>
                       <p>{{ article.body }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>4 comments</h2>
                    </div>
                    <div class="content">
                      <ul>

                          {% for comment in article.comments.all %}
                              {% if comment.parent == None %}
                                  <li>
                          <div class="author-thumb">
                            {% if comment.user.profile.image %}
                                <img src="{{ comment.user.profile.image.url }}" alt="">
                            {% else %}
                                <img src="{% static 'images/comment-author-02.jpg' %}" alt="">
                            {% endif %}
                          </div>
                          <div class="right-content">
                            <h4>{{ comment.user.get_full_name }}<span>{{ comment.created_at }}</span></h4>
                            <p>{{ comment.body }}</p>
                             <button onclick="set_value({{ comment.id }})" class="btn btn-primary">reply</button>
                          </div>
                          </li>
                           {% for reply in comment.replies.all %}
                                <li class="replied">
                          <div class="author-thumb">
                             {% if reply.user.profile.image %}
                                <img src="{{ reply.user.profile.image.url }}" alt="">
                            {% else %}
                                <img src="{% static 'images/comment-author-02.jpg' %}" alt="">
                            {% endif %}
                          </div>
                          <div class="right-content">
                            <h4>{{ reply.user.get_full_name }}<span>{{ reply.created_at }}</span></h4>
                            <p>{{ reply.body }}</p>
                          </div>
                        </li>
                           {% endfor %}
                              {% endif %}
                          {% endfor %}
                      </ul>

                    </div>
                  </div>
                </div>

              {% if request.user.is_authenticated %}
                   <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                      <form id="comment" action="#" method="post">
                          {% csrf_token %}
                        <div class="row">
                          <input type="hidden" id="parent_id" name="parent_id" value="">
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="body" rows="6" id="body" placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                  {% else %}
                  <a class="btn btn-danger" href="{% url 'account:login' %}">for send comment Please login</a>
              {% endif %}

              </div>
            </div>
          </div>
          {% include "includes/sidebar.html" %}
        </div>
      </div>
    </section>
<script>
  function set_value(id){
      document.getElementById('parent_id').value = id;
      window.location.href= "#body"
  }

</script>

{% endblock %}

    


    

blog/templates/blog/article_details.html
{% extends 'base.html' %}
{% load static   %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}

      <!-- Banner Ends Here -->
    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src={{ article.image.url }} alt="">
                    </div>
                    <div class="down-content">
                      <span>Lifestyle</span>
                      <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.auther }}</a></li>
                        <li><a href="#">{{ article.created }}</a></li>
                        <li><a href="#">10 Comments</a></li>
                      </ul>
                       <p>{{ article.body }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>4 comments</h2>
                    </div>
                    <div class="content">
                      <ul>

                          {% for comment in article.comments.all %}
                              {% if comment.parent == None %}
                                  <li>
                          <div class="author-thumb">
                            {% if comment.user.profile.image %}
                                <img src="{{ comment.user.profile.image.url }}" alt="">
                            {% else %}
                                <img src="{% static 'images/comment-author-02.jpg' %}" alt="">
                            {% endif %}
                          </div>
                          <div class="right-content">
                            <h4>{{ comment.user.get_full_name }}<span>{{ comment.created_at }}</span></h4>
                            <p>{{ comment.body }}</p>
                             <button onclick="set_value({{ comment.id }})" class="btn btn-primary">reply</button>
                          </div>
                          </li>
                           {% for reply in comment.replies.all %}
                                <li class="replied">
                          <div class="author-thumb">
                             {% if reply.user.profile.image %}
                                <img src="{{ reply.user.profile.image.url }}" alt="">
                            {% else %}
                                <img src="{% static 'images/comment-author-02.jpg' %}" alt="">
                            {% endif %}
                          </div>
                          <div class="right-content">
                            <h4>{{ reply.user.get_full_name }}<span>{{ reply.created_at }}</span></h4>
                            <p>{{ reply.body }}</p>
                          </div>
                        </li>
                           {% endfor %}
                              {% endif %}
                          {% endfor %}
                      </ul>

                    </div>
                  </div>
                </div>

              {% if request.user.is_authenticated %}
                   <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                      <form id="comment" action="#" method="post">
                          {% csrf_token %}
                        <div class="row">
                          <input type="hidden" id="parent_id" name="parent_id" value="">
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="body" rows="6" id="body" placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                  {% else %}
                  <a class="btn btn-danger" href="{% url 'account:login' %}">for send comment Please login</a>
              {% endif %}

              </div>
            </div>
          </div>
          {% include "includes/sidebar.html" %}
        </div>
      </div>
    </section>
<script>
  function set_value(id){
      document.getElementById('parent_id').value = id;
      window.location.href= "#body"
  }

</script>

{% endblock %}

    


    

blog/templates/blog/contact_us.html
{% extends "base.html" %}
{% load static %}
{% block title %}contact us{% endblock %}
{% block content %}

    <section class="contact-us">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        <form id="contact" action="" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12">
                                               {{ form.non_field_errors }}
                                                   {% if form.name.errors %}
                                                    <div class="alert alert-danger">{{ form.name.errors }}</div>
                                                    {% endif %}
                                                    {{ form.name }}
                                                {% if form.text.errors %}
                                                    <div class="alert alert-danger">{{ form.text.errors }}</div>
                                                    {% endif %}
                                                    {{ form.text }}
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">Send
                                                            Message
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="sidebar-item contact-information">
                                    <div class="sidebar-heading">
                                        <h2>contact information</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            <li>
                                                <h5>090-484-8080</h5>
                                                <span>PHONE NUMBER</span>
                                            </li>
                                            <li>
                                                <h5>info@company.com</h5>
                                                <span>EMAIL ADDRESS</span>
                                            </li>
                                            <li>
                                                <h5>123 Aenean id posuere dui,
                                                    <br>Praesent laoreet 10660</h5>
                                                <span>STREET ADDRESS</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

blog/templates/blog/message_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
   <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

blog/templates/blog/message_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Message List</title>
</head>
<body>
{% for item in message_list %}
    <p>{{ item.title }} - {{ item.text|truncatewords:20 }} - {{ item.email }} -<span><a href="{% url 'blog:message_edit' item.id %}" >Edit</a></span></p>
    <hr>
{% endfor %}
</body>
</html>

blog/templates/blog/message_update_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}contact us{% endblock %}
{% block content %}

    <section class="contact-us">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        <form id="contact" action="" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-lg-12">
                                                  {{ form }}
                                                <div class="col-lg-12">
                                                    <a href="{% url 'blog:message_delete' object.id %}" class="btn btn-danger">Delete</a>
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">
                                                           Submit
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="sidebar-item contact-information">
                                    <div class="sidebar-heading">
                                        <h2>contact information</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            <li>
                                                <h5>090-484-8080</h5>
                                                <span>PHONE NUMBER</span>
                                            </li>
                                            <li>
                                                <h5>info@company.com</h5>
                                                <span>EMAIL ADDRESS</span>
                                            </li>
                                            <li>
                                                <h5>123 Aenean id posuere dui,
                                                    <br>Praesent laoreet 10660</h5>
                                                <span>STREET ADDRESS</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}